### ISSUE TITLE
Use with nii files

### ISSUE THREAD

**Issue by AmericaBG** [PanPapag/Zero-Learning-Fast-Medical-Image-Fusion#1]
Hi!
First of all, thank you very much for sharing your great job, congratulations!

I work with a dataset of medical images in .nii format. Could you say me if would be posible to use your image fusion code with that format? 

Thank you very much in advance!

**Comment by PanPapag** [comment]
Sure I would love to! Keep me updated if there is anything I can do for you.

Good luck!

**Comment by AmericaBG** [comment]
Hello again! 😅

My problem is that I don't know how to do it. Could you give some advice about how can I use your code with .nii format and/or what should I modify?

Thanks :)
